const API_BASE = 'https://shopcompare-v2.onrender.com';

const demoProducts = [
  {id:'1', name:'Apple AirPods Pro (2nd Generation) USB-C', store:'Amazon', price:189.99, rating:4.6, reviews:18542, shipping:'Free shipping', delivery:'2–3 days', emoji:'🎧', keywords:'wireless earbuds airpods headphones apple', score:96, productUrl:'https://www.amazon.com/'},
  {id:'2', name:'Wireless Bluetooth Earbuds with Noise Cancelling', store:'Temu', price:12.48, rating:4.4, reviews:8731, shipping:'Free shipping', delivery:'6–10 days', emoji:'🎧', keywords:'wireless earbuds bluetooth headphones', score:82, productUrl:'https://www.temu.com/'},
  {id:'3', name:'Wireless Earbuds Bluetooth 5.3 In-Ear Headphones', store:'SHEIN', price:15.20, rating:4.3, reviews:5102, shipping:'$3.99 shipping', delivery:'5–8 days', emoji:'🎧', keywords:'wireless earbuds bluetooth headphones', score:80, productUrl:'https://www.shein.com/'},
  {id:'4', name:'JBL Tune Wireless Earbuds', store:'Walmart', price:39.88, rating:4.5, reviews:3221, shipping:'Free shipping', delivery:'2–4 days', emoji:'🎶', keywords:'wireless earbuds jbl bluetooth headphones', score:90, productUrl:'https://www.walmart.com/'},
  {id:'5', name:'Pro 6 Bluetooth Earphones Touch Control', store:'AliExpress', price:9.95, rating:4.2, reviews:12901, shipping:'Free shipping', delivery:'8–14 days', emoji:'🎧', keywords:'wireless earbuds bluetooth earphones', score:76, productUrl:'https://www.aliexpress.com/'}
];

let products = [];
let state = {query:'wireless earbuds', maxPrice:250, stores:new Set(['Amazon','Temu','SHEIN','Walmart','AliExpress']), minRating:0, freeShipping:false, sort:'best', compare:new Set(), favorites:new Set(), loading:false};
const $ = s => document.querySelector(s); const $$ = s => [...document.querySelectorAll(s)];
const productList=$('#productList'), queryLabel=$('#queryLabel'), resultCount=$('#resultCount'), emptyState=$('#emptyState');
function storeClass(store){return store.toLowerCase().replace('aliexpress','ali')}
function localFallback(query){const q=String(query||'').trim().toLowerCase();return demoProducts.filter(p=>!q||`${p.name} ${p.keywords} ${p.store}`.toLowerCase().includes(q));}
async function fetchProducts(query){state.loading=true;render();try{const r=await fetch(`${API_BASE}/api/search?q=${encodeURIComponent(query||'')}`);if(!r.ok)throw new Error(`API ${r.status}`);const data=await r.json();products=(data.results||[]).map(p=>({...p,id:String(p.id),emoji:p.store==='Walmart'?'🎶':'🎧',keywords:`${p.name} ${p.store}`,score:p.valueScore ?? (p.rating?Math.round(p.rating*20):0)}));}catch(e){console.warn('API unavailable; using local demo data.',e);products=localFallback(query);}finally{state.loading=false;render();}}
function filtered(){let arr=products.filter(p=>p.price<=state.maxPrice&&state.stores.has(p.store)&&(p.rating==null||p.rating>=state.minRating)&&(!state.freeShipping||p.shipping==='Free shipping'));if(state.sort==='priceLow')arr.sort((a,b)=>a.price-b.price);else if(state.sort==='rating')arr.sort((a,b)=>(b.rating||0)-(a.rating||0));else arr.sort((a,b)=>(b.score||0)-(a.score||0));return arr;}
function render(){const arr=filtered();queryLabel.textContent=state.query||'all products';resultCount.textContent=state.loading?'…':arr.length;productList.innerHTML='';if(state.loading)productList.innerHTML='<div class="empty-state">Searching stores…</div>';emptyState.classList.toggle('hidden',state.loading||arr.length!==0);arr.forEach(p=>{const card=document.createElement('article');card.className='product-card';const rating=p.rating==null?'N/A':`${p.rating} (${(p.reviews||0).toLocaleString()})`;card.innerHTML=`<div class="product-image">${p.emoji||'🛍️'}</div><div class="product-meta"><div class="store-label ${storeClass(p.store)}">${p.store}</div><h3>${p.name}</h3><p><span class="rating">★★★★★</span> ${rating}</p>${p.shipping?`<span class="shipping">${p.shipping}</span>`:''}${p.delivery?`<p>Estimated delivery: ${p.delivery}</p>`:''}</div><div class="product-actions"><div class="price">$${Number(p.price||0).toFixed(2)}</div><div class="action-row"><button class="icon-btn ${state.favorites.has(String(p.id))?'active':''}" data-fav="${p.id}">${state.favorites.has(String(p.id))?'♥':'♡'}</button><button class="outline-btn ${state.compare.has(String(p.id))?'selected':''}" data-compare="${p.id}">${state.compare.has(String(p.id))?'Selected':'Compare'}</button><button class="deal-btn" data-deal="${p.id}">View on ${p.store} →</button></div></div>`;productList.appendChild(card);});$('#compareCount').textContent=state.compare.size;$('#favoriteCount').textContent=state.favorites.size;renderCompare();}
function renderCompare(){const chosen=products.filter(p=>state.compare.has(String(p.id)));const grid=$('#compareGrid');grid.innerHTML='';if(!chosen.length){grid.innerHTML='<div class="compare-card">Choose up to 3 products to compare.</div>';return;}chosen.forEach(p=>{const el=document.createElement('div');el.className='compare-card';el.innerHTML=`<div class="product-image">${p.emoji||'🛍️'}</div><div class="store-label ${storeClass(p.store)}">${p.store}</div><h3>${p.name}</h3><div class="price">$${Number(p.price||0).toFixed(2)}</div><dl><dt>Rating</dt><dd>${p.rating??'N/A'} ★</dd><dt>Shipping</dt><dd>${p.shipping||'Not provided'}</dd><dt>Delivery</dt><dd>${p.delivery||'Not provided'}</dd><dt>Value score</dt><dd>${p.score??'—'}/100</dd></dl><button class="deal-btn" data-deal="${p.id}">View on ${p.store} →</button></div>`;grid.appendChild(el);});}
async function setQuery(q){state.query=String(q||'').trim();$('#heroSearch').value=state.query;$('#resultsSearch').value=state.query;location.hash='results';await fetchProducts(state.query);}
$('#heroSearchForm').addEventListener('submit',e=>{e.preventDefault();setQuery($('#heroSearch').value)});$('#resultsSearchForm').addEventListener('submit',e=>{e.preventDefault();setQuery($('#resultsSearch').value)});$$('[data-query]').forEach(b=>b.addEventListener('click',()=>setQuery(b.dataset.query)));
$('#priceRange').addEventListener('input',e=>{state.maxPrice=+e.target.value;$('#priceValue').textContent=`$${state.maxPrice}`;render()});$$('.store-filter').forEach(cb=>cb.addEventListener('change',e=>{e.target.checked?state.stores.add(e.target.value):state.stores.delete(e.target.value);render()}));$('#ratingFilter').addEventListener('change',e=>{state.minRating=+e.target.value;render()});$('#freeShipping').addEventListener('change',e=>{state.freeShipping=e.target.checked;render()});$('#sortSelect').addEventListener('change',e=>{state.sort=e.target.value;render()});$('#clearFilters').addEventListener('click',()=>{state.maxPrice=250;state.stores=new Set(['Amazon','Temu','SHEIN','Walmart','AliExpress']);state.minRating=0;state.freeShipping=false;$('#priceRange').value=250;$('#priceValue').textContent='$250';$$('.store-filter').forEach(x=>x.checked=true);$('#ratingFilter').value='0';$('#freeShipping').checked=false;render()});
document.addEventListener('click',e=>{const c=e.target.closest('[data-compare]');if(c){const id=String(c.dataset.compare);if(state.compare.has(id))state.compare.delete(id);else if(state.compare.size<3)state.compare.add(id);else alert('You can compare up to 3 products at a time.');render()}const f=e.target.closest('[data-fav]');if(f){const id=String(f.dataset.fav);state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);render()}const d=e.target.closest('[data-deal]');if(d){const p=products.find(x=>String(x.id)===String(d.dataset.deal));if(p?.productUrl)window.open(p.productUrl,'_blank','noopener');else alert('No retailer link is available for this product yet.');}});
$('#compareToggle').addEventListener('click',()=>$('#comparePanel').classList.remove('hidden'));$('#closeCompare').addEventListener('click',()=>$('#comparePanel').classList.add('hidden'));$('#favoritesBtn').addEventListener('click',()=>{if(!state.favorites.size)return alert('You have not saved any favorites yet.');const ids=new Set(state.favorites);products=products.filter(p=>ids.has(String(p.id)));state.query='';render();location.hash='results';});$$('[data-home]').forEach(a=>a.addEventListener('click',()=>{location.hash='home'}));

let opportunities = [];
function opportunityCard(p){
  const verdictClass=p.opportunityVerdict==='Strong candidate'?'strong':p.opportunityVerdict==='Weak candidate'?'weak':'';
  const reasons=(p.opportunityReasons||[]).map(x=>`<li>${x}</li>`).join('');
  return `<article class="opportunity-card"><div class="opportunity-top"><div><div class="opportunity-store">${p.store}</div><h3>${p.name}</h3><div class="opportunity-category">${p.category||'Other'} · ${p.competition||'Unknown'} competition</div></div><div class="opportunity-score"><strong>${p.opportunityScore}</strong><span>OPPORTUNITY</span></div></div><span class="opportunity-verdict ${verdictClass}">${p.opportunityVerdict}</span><div class="opportunity-metrics"><div class="opportunity-metric"><span>Landed cost</span><strong>$${Number(p.estimatedLandedCost||0).toFixed(2)}</strong></div><div class="opportunity-metric"><span>Suggested test price</span><strong>$${Number(p.estimatedTestPrice||0).toFixed(2)}</strong></div><div class="opportunity-metric"><span>Est. gross profit</span><strong>$${Number(p.estimatedGrossProfit||0).toFixed(2)}</strong></div><div class="opportunity-metric"><span>Est. gross margin</span><strong>${Number(p.estimatedGrossMargin||0).toFixed(1)}%</strong></div></div><ul class="opportunity-reasons">${reasons}</ul><div class="opportunity-foot"><span>Rating ${p.rating??'N/A'} · ${(p.reviews||0).toLocaleString()} reviews</span><button class="deal-btn" data-opportunity-deal="${p.id}">View product →</button></div></article>`;
}
function renderOpportunities(){const min=Number($('#opportunityScore').value);const list=$('#opportunityList');const visible=opportunities.filter(p=>p.opportunityScore>=min);$('#opportunityScoreValue').textContent=min;list.innerHTML=visible.length?visible.map(opportunityCard).join(''):'<div class="empty-state">No opportunities meet this score. Lower the minimum score or try another search.</div>';}
async function fetchOpportunities(query){const status=$('#opportunityStatus');const list=$('#opportunityList');status.textContent='Analyzing product signals…';list.innerHTML='<div class="empty-state">Finding and scoring opportunities…</div>';try{const stores=[...state.stores].join(',');const r=await fetch(`${API_BASE}/api/opportunities?q=${encodeURIComponent(query||'')}&stores=${encodeURIComponent(stores)}&minScore=0`);if(!r.ok)throw new Error(`API ${r.status}`);const data=await r.json();opportunities=data.results||[];status.textContent=`${opportunities.length} opportunities found. Score is a screening estimate, not a sales guarantee.`;renderOpportunities();}catch(e){console.warn('Opportunity API unavailable.',e);opportunities=[];status.textContent='The opportunity engine is currently unavailable. Start the backend/API before using Product Finder.';list.innerHTML='';}}
$('#opportunityForm').addEventListener('submit',e=>{e.preventDefault();fetchOpportunities($('#opportunityQuery').value.trim())});$('#opportunityScore').addEventListener('input',renderOpportunities);document.addEventListener('click',e=>{const b=e.target.closest('[data-opportunity-deal]');if(!b)return;const p=opportunities.find(x=>String(x.id)===String(b.dataset.opportunityDeal));if(p?.productUrl)window.open(p.productUrl,'_blank','noopener');});

fetchProducts(state.query);fetchOpportunities($('#opportunityQuery').value);
